[package]
name = "ufo_rs"
version = "0.1.0"
license = "MIT"
description = "A `Drone/UAV/Quad copter programming library for Rust`"
authors = ["Avery Wagar <ajmw.subs@gmail.com>"]
edition = "2018"

[dependencies]
hex = "*"
